version: '3'

services:
  db:
    image: postgresql
    container_name: database
    restart: always
  rabbitMQ:
    image: rabbitmq:latest
    container_name: rabbitMQ
  consumer:
    image: katevorob/consumer
    container_name: consumer
